image: docker:stable

services:
  - docker:dind

variables:
  VCS_REF: "${CI_COMMIT_SHA}"
  VCS_URL: "${CI_PROJECT_URL}"
  DOCKER_REPO: "${CI_REGISTRY_IMAGE}"
  DOCKER_TAG: "${CI_COMMIT_REF_NAME}"

build_and_push:
  script:
    - docker info
    - if [ "master" = "${DOCKER_TAG}" ]; then export DOCKER_TAG=latest; fi
    - ./hooks/build
    - docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
    - docker image push "${DOCKER_REPO}:${DOCKER_TAG}"
