image: docker:stable

services:
  - docker:dind

variables:
  VCS_REF: $CI_COMMIT_SHA
  VCS_URL: $CI_PROJECT_URL
  IMAGE_NAME: $CI_REGISTRY_IMAGE

before_script:
  - docker info

build_image:
  script:
    - ./hooks/build

after_script:
  - docker image push $CI_REGISTRY_IMAGE
