image: docker:stable

services:
  - docker:dind

variables:
  VCS_REF: $CI_COMMIT_SHA
  VCS_URL: $CI_PROJECT_URL
  IMAGE_NAME: $CI_REGISTRY_IMAGE

before_script:
  - docker info

build_image:
  script:
    - ./hooks/build

after_script:
  - docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
  - docker image push "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}"
  - docker image push "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}"
  - if [ "master" = "${CI_COMMIT_REF_NAME}" ]; then docker image push "${CI_REGISTRY_IMAGE}:latest"; fi
