#!/bin/sh

# bloomer/configure-rosdep

set -eu

readonly this="$(readlink -f "$0")"
readonly here="$(dirname "${this}")"
readonly whatami="$(basename "${here}").$(basename "${this}")"
readonly tmpdir="$(mktemp -dt "${whatami}.XXXXXX")"

log() { echo "${whatami}[$$]: $@" >&2; }
error() { log "ERROR: $@"; }
warning() { log "WARNING: $@"; }
info() { log "INFO: $@"; }

die() {
    error "$@"
    usage >&2
    exit 1
}

cleanup() {
    status="$?"
    rm -rf "${tmpdir}"
    return "${status}"
}

usage() {
    cat <<EOF
Usage: $(basename ${this})
Configure rosdistro to use additional repositories.

Examples:

    \$ $(basename ${this})
EOF
}

################################################################################

trap cleanup EXIT
export TMPDIR="${tmpdir}"
export LC_ALL=C

if ! [ 0 -eq "$(id -u)" ]; then
    sudo "${this}"
    exit "$?"
fi

while getopts ":h" opt; do
    case "${opt}" in
        h)
            usage
            exit 0
            ;;
        :) die "missing argument: -${OPTARG}" ;;
        \?) die "bad option: -${OPTARG}" ;;
    esac
done
shift "$((${OPTIND} - 1))"

info "discovering realsense packages"
readonly realsense_package_list="$(mktemp -t realsense.package.list.XXXXXX)"
find /var/lib/apt/lists -type f \
     -a \( -name 'realsense*_Packages'     -exec cat       {} \; \) \
     -o \( -name 'realsense*_Packages.bz2' -exec bzip2 -dc {} \; \) \
     -o \( -name 'realsense*_Packages.gz'  -exec gzip  -dc {} \; \) \
     -o \( -name 'realsense*_Packages.lz4' -exec lz4   -dc {} \; \) \
     -o \( -name 'realsense*_Packages.xz'  -exec xz    -dc {} \; \) \
    | sed -nr 's|^Package:[[:space:]]+([[:graph:]]+).*$|\1|gp' \
          >"${realsense_package_list}"
sort -uo "${realsense_package_list}" "${realsense_package_list}"

readonly realsense_yaml="/var/rosdep/realsense.yaml"
info "generating ${realsense_yaml}"
mkdir -vp "$(dirname "${realsense_yaml}")"
cat >"${realsense_yaml}" <<EOF
# ${realsense_yaml}
#
# THIS IS A GENERATED FILE
# generator : ${this}
# user      : $(id)
# uname     : $(uname -a)
# date      : $(date -u +"%Y-%m-%dT%H:%M:%SZ")

EOF

while read realsense_package; do
    cat >>"${realsense_yaml}" <<EOF
${realsense_package}:
  ubuntu: [${realsense_package}]
EOF
done <"${realsense_package_list}"

readonly realsense_list="/etc/ros/rosdep/sources.list.d/00-realsense.list"
info "generating ${realsense_list}"
mkdir -vp "$(dirname "${realsense_list}")"
cat >"${realsense_list}" <<EOF
# ${realsense_list}
#
# THIS IS A GENERATED FILE
# generator : ${this}
# user      : $(id)
# uname     : $(uname -a)
# date      : $(date -u +"%Y-%m-%dT%H:%M:%SZ")

yaml file://${realsense_yaml}
EOF
